[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.1"
anyhow = "1.0"
bit-vec = "0.6"
paste = "1.0"
regex = "1.7.1"
resvg = "0.29"
usvg = "0.29"
walkdir = "2.3.3"
